trainer: energy

dataset:
  - src: /home/jovyan/tmQM_rev/training_data/tmQM/40-train.lmdb 
    normalize_labels: True
    target_mean: -0.0000000000007721791308318971
    target_std: 0.1262288707145667 
  - src: /home/jovyan/tmQM_rev/training_data/tmQM/40-val.lmdb 
  - src: /home/jovyan/tmQM_rev/training_data/tmQM/40-test.lmdb

logger: wandb

task:
  dataset: single_point_lmdb
  description: "Relaxed state energy prediction from initial structure."
  type: regression
  metric: mae
  labels:
    - relaxed energy

model:
  name: painn
  hidden_channels: 1024
  num_layers: 6
  num_rbf: 128
  cutoff: 12.0
  max_neighbors: 50
  scale_file: configs/s2ef/all/painn/painn_nb6_scaling_factors.pt
  regress_forces: False
  use_pbc: False
  otf_graph: True

optim:
  batch_size: 16
  eval_batch_size: 16
  load_balancing: atoms
  num_workers: 2
  optimizer: AdamW
  optimizer_params: {"amsgrad": True}
  lr_initial: 1.e-4
  scheduler: ReduceLROnPlateau
  mode: min
  factor: 0.8
  patience: 3
  max_epochs: 80
  energy_coefficient: 1
  ema_decay: 0.999
  clip_grad_norm: 10
  loss_energy: mae
  weight_decay: 0  # 2e-6 (TF weight decay) / 1e-4 (lr) = 2e-2