trainer: energy

dataset:
  - src: ../tmQM_rev/training_data/tmQM_neutral/40-train.lmdb
    normalize_labels: True
    target_mean: 0.0000000000016765290442458564
    target_std: 0.10930832134571512
  - src: ../tmQM_rev/training_data/tmQM_neutral/40-val.lmdb
  - src: ../tmQM_rev/training_data/tmQM_neutral/40-test.lmdb

logger: wandb

task:
  dataset: single_point_lmdb
  description: "Relaxed state energy prediction from initial structure."
  type: regression
  metric: mae
  labels:
    - relaxed energy

model:
  name: schnet
  hidden_channels: 384
  num_filters: 128
  num_interactions: 4
  num_gaussians: 100
  cutoff: 6.0
  use_pbc: False
  regress_forces: False
  otf_graph: True

# *** Important note ***
#   The total number of gpus used for this run was 1.
#   If the global batch size (num_gpus * batch_size) is modified
#   the lr_milestones and warmup_steps need to be adjusted accordingly.

optim:
  batch_size: 32
  eval_batch_size: 32
  num_workers: 16
  lr_initial: 0.0005
  lr_gamma: 0.1
  lr_milestones: # steps at which lr_initial <- lr_initial * lr_gamma
    - 7812
    - 15625
    - 23438
  warmup_steps: 4688
  warmup_factor: 0.2
  max_epochs: 30
