trainer: energy

dataset:
  - src: ../tmQM_rev/training_data/tmQM_neutral/40-train.lmdb
    normalize_labels: True
    target_mean: 0.0000000000016765290442458564
    target_std: 0.10930832134571512
  - src: ../tmQM_rev/training_data/tmQM_neutral/40-val.lmdb
  - src: ../tmQM_rev/training_data/tmQM_neutral/40-test.lmdb

logger: wandb

task:
  dataset: single_point_lmdb
  description: "Relaxed state energy prediction from initial structure."
  type: regression
  metric: mae
  labels:
    - relaxed energy
  train_on_free_atoms: True
  eval_on_free_atoms: True
  
model:
  name: spinconv
  model_ref_number: 0
  hidden_channels: 32
  mid_hidden_channels: 256
  num_interactions: 3
  num_basis_functions: 512
  sphere_size_lat: 16
  sphere_size_long: 12
  max_num_neighbors: 40
  cutoff: 6.0
  sphere_message: fullconv
  output_message: fullconv
  force_estimator: random
  regress_forces: False
  scale_distances: True
  basis_width_scalar: 3.0
  use_pbc: False
  otf_graph: True

optim:
  batch_size: 3
  eval_batch_size: 3
  num_workers: 8
  lr_initial: 0.0004
  optimizer: Adam
  optimizer_params: {"amsgrad": True}
  eval_every: 5000
  scheduler: ReduceLROnPlateau
  mode: min
  factor: 0.8
  patience: 3
  max_epochs: 80
  force_coefficient: 100
  energy_coefficient: 1